package com.edu.ubosque.model;
// Generated 23/11/2020, 6:36:43 p. m. by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clase que modela un ciudadano
 * Ciudadano generated by hbm2java
 * @author Nicolás Ávila, Sebastián Moncaleano, Diego Torres | Universidad El Bosque
 */
@Entity
@Table(name = "ciudadano")
public class Ciudadano implements java.io.Serializable {

	private int id;
	private String usuario;
	private String clave;
	private String primerNombre;
	private String segundoNombre;
	private String primerApellido;
	private String segundoApellido;
	private Date fechaNacimiento;
	private String lugarNacimiento;
	private String direccion;
	private String telefono;
	private String estadoCivil;
	private String correoElectronico;
	private String perfilProfesional;
	private double aspiracionLaboral;
	private String horario;
	private Set<ExperienciaLaboral> experienciaLaborals = new HashSet<ExperienciaLaboral>(0);
	private Set<Referencias> referenciases = new HashSet<Referencias>(0);
	private Set<PostulacionLaboral> postulacionLaborals = new HashSet<PostulacionLaboral>(0);
	private Set<InformacionAcademica> informacionAcademicas = new HashSet<InformacionAcademica>(0);

	public Ciudadano() {
	}

	public Ciudadano(int id, String usuario, String clave, String primerNombre, String segundoNombre,
			String primerApellido, String segundoApellido, Date fechaNacimiento, String lugarNacimiento,
			String direccion, String telefono, String estadoCivil, String correoElectronico, String perfilProfesional,
			double aspiracionLaboral, String horario) {
		this.id = id;
		this.usuario = usuario;
		this.clave = clave;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.fechaNacimiento = fechaNacimiento;
		this.lugarNacimiento = lugarNacimiento;
		this.direccion = direccion;
		this.telefono = telefono;
		this.estadoCivil = estadoCivil;
		this.correoElectronico = correoElectronico;
		this.perfilProfesional = perfilProfesional;
		this.aspiracionLaboral = aspiracionLaboral;
		this.horario = horario;
	}


	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "usuario", nullable = false, length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "clave", nullable = false, length = 45)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "primer_nombre", nullable = false, length = 45)
	public String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	@Column(name = "segundo_nombre", length = 45)
	public String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	@Column(name = "primer_apellido", nullable = false, length = 45)
	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	@Column(name = "segundo_apellido", length = 45)
	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", nullable = false, length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "lugar_nacimiento", nullable = false, length = 45)
	public String getLugarNacimiento() {
		return this.lugarNacimiento;
	}

	public void setLugarNacimiento(String lugarNacimiento) {
		this.lugarNacimiento = lugarNacimiento;
	}

	@Column(name = "direccion", nullable = false, length = 45)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", nullable = false, length = 15)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "estado_civil", nullable = false, length = 45)
	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@Column(name = "correo_electronico", nullable = false, length = 60)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "perfil_profesional", nullable = false, length = 200)
	public String getPerfilProfesional() {
		return this.perfilProfesional;
	}

	public void setPerfilProfesional(String perfilProfesional) {
		this.perfilProfesional = perfilProfesional;
	}

	@Column(name = "aspiracion_laboral", nullable = false, precision = 22, scale = 0)
	public double getAspiracionLaboral() {
		return this.aspiracionLaboral;
	}

	public void setAspiracionLaboral(double aspiracionLaboral) {
		this.aspiracionLaboral = aspiracionLaboral;
	}

	@Column(name = "horario", nullable = false, length = 45)
	public String getHorario() {
		return this.horario;
	}

	public void setHorario(String horario) {
		this.horario = horario;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "ciudadano")
	public Set<ExperienciaLaboral> getExperienciaLaborals() {
		return this.experienciaLaborals;
	}

	public void setExperienciaLaborals(Set<ExperienciaLaboral> experienciaLaborals) {
		this.experienciaLaborals = experienciaLaborals;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "ciudadano")
	public Set<Referencias> getReferenciases() {
		return this.referenciases;
	}

	public void setReferenciases(Set<Referencias> referenciases) {
		this.referenciases = referenciases;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "ciudadano")
	public Set<PostulacionLaboral> getPostulacionLaborals() {
		return this.postulacionLaborals;
	}

	public void setPostulacionLaborals(Set<PostulacionLaboral> postulacionLaborals) {
		this.postulacionLaborals = postulacionLaborals;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "ciudadano")
	public Set<InformacionAcademica> getInformacionAcademicas() {
		return this.informacionAcademicas;
	}

	public void setInformacionAcademicas(Set<InformacionAcademica> informacionAcademicas) {
		this.informacionAcademicas = informacionAcademicas;
	}

}
