package com.edu.ubosque.model;
// Generated 13/11/2020, 9:41:30 p. m. by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ciudadano generated by hbm2java
 */
@Entity
@Table(name = "ciudadano")
public class Ciudadano implements java.io.Serializable {

	private int id;
	private ExperienciaLaboral experienciaLaboral;
	private InformacionAcademica informacionAcademica;
	private Referencias referencias;
	private String usuario;
	private String clave;
	private String primerNombre;
	private String segundoNombre;
	private String primerApellido;
	private String segundoApellido;
	private Date fechaNacimiento;
	private String lugarNacimiento;
	private String direccion;
	private int telefono;
	private String estadoCivil;
	private String correoElectronico;
	private String perfilProfesional;
	private double aspiracionLaboral;
	private String horario;

	public Ciudadano() {
	}

	public Ciudadano(int id, ExperienciaLaboral experienciaLaboral, InformacionAcademica informacionAcademica,
			Referencias referencias, String usuario, String clave, String primerNombre, String primerApellido,
			Date fechaNacimiento, String lugarNacimiento, String direccion, int telefono, String estadoCivil,
			String correoElectronico, String perfilProfesional, double aspiracionLaboral, String horario) {
		this.id = id;
		this.experienciaLaboral = experienciaLaboral;
		this.informacionAcademica = informacionAcademica;
		this.referencias = referencias;
		this.usuario = usuario;
		this.clave = clave;
		this.primerNombre = primerNombre;
		this.primerApellido = primerApellido;
		this.fechaNacimiento = fechaNacimiento;
		this.lugarNacimiento = lugarNacimiento;
		this.direccion = direccion;
		this.telefono = telefono;
		this.estadoCivil = estadoCivil;
		this.correoElectronico = correoElectronico;
		this.perfilProfesional = perfilProfesional;
		this.aspiracionLaboral = aspiracionLaboral;
		this.horario = horario;
	}

	public Ciudadano(int id, ExperienciaLaboral experienciaLaboral, InformacionAcademica informacionAcademica,
			Referencias referencias, String usuario, String clave, String primerNombre, String segundoNombre,
			String primerApellido, String segundoApellido, Date fechaNacimiento, String lugarNacimiento,
			String direccion, int telefono, String estadoCivil, String correoElectronico, String perfilProfesional,
			double aspiracionLaboral, String horario) {
		this.id = id;
		this.experienciaLaboral = experienciaLaboral;
		this.informacionAcademica = informacionAcademica;
		this.referencias = referencias;
		this.usuario = usuario;
		this.clave = clave;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.fechaNacimiento = fechaNacimiento;
		this.lugarNacimiento = lugarNacimiento;
		this.direccion = direccion;
		this.telefono = telefono;
		this.estadoCivil = estadoCivil;
		this.correoElectronico = correoElectronico;
		this.perfilProfesional = perfilProfesional;
		this.aspiracionLaboral = aspiracionLaboral;
		this.horario = horario;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_exp_laboral", nullable = false)
	public ExperienciaLaboral getExperienciaLaboral() {
		return this.experienciaLaboral;
	}

	public void setExperienciaLaboral(ExperienciaLaboral experienciaLaboral) {
		this.experienciaLaboral = experienciaLaboral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_info_academica", nullable = false)
	public InformacionAcademica getInformacionAcademica() {
		return this.informacionAcademica;
	}

	public void setInformacionAcademica(InformacionAcademica informacionAcademica) {
		this.informacionAcademica = informacionAcademica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_referencias", nullable = false)
	public Referencias getReferencias() {
		return this.referencias;
	}

	public void setReferencias(Referencias referencias) {
		this.referencias = referencias;
	}

	@Column(name = "usuario", nullable = false, length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "clave", nullable = false, length = 45)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "primer_nombre", nullable = false, length = 45)
	public String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	@Column(name = "segundo_nombre", length = 45)
	public String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	@Column(name = "primer_apellido", nullable = false, length = 45)
	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	@Column(name = "segundo_apellido", length = 45)
	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", nullable = false, length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "lugar_nacimiento", nullable = false, length = 45)
	public String getLugarNacimiento() {
		return this.lugarNacimiento;
	}

	public void setLugarNacimiento(String lugarNacimiento) {
		this.lugarNacimiento = lugarNacimiento;
	}

	@Column(name = "direccion", nullable = false, length = 45)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", nullable = false)
	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	@Column(name = "estado_civil", nullable = false, length = 45)
	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@Column(name = "correo_electronico", nullable = false, length = 60)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "perfil_profesional", nullable = false, length = 200)
	public String getPerfilProfesional() {
		return this.perfilProfesional;
	}

	public void setPerfilProfesional(String perfilProfesional) {
		this.perfilProfesional = perfilProfesional;
	}

	@Column(name = "aspiracion_laboral", nullable = false, precision = 22, scale = 0)
	public double getAspiracionLaboral() {
		return this.aspiracionLaboral;
	}

	public void setAspiracionLaboral(double aspiracionLaboral) {
		this.aspiracionLaboral = aspiracionLaboral;
	}

	@Column(name = "horario", nullable = false, length = 45)
	public String getHorario() {
		return this.horario;
	}

	public void setHorario(String horario) {
		this.horario = horario;
	}

}
