package com.edu.ubosque.model;
// Generated 17/11/2020, 8:53:57 p. m. by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OfertaLaboral generated by hbm2java
 */
@Entity
@Table(name = "oferta_laboral")
public class OfertaLaboral implements java.io.Serializable {

	private int idOferta;
	private Empresa empresa;
	private String cargo;
	private String area;
	private Date aniosExperiencia;
	private String profesion;
	private String nivelEstudios;
	private String tipoContrato;
	private double salario;

	public OfertaLaboral() {
	}

	public OfertaLaboral(int idOferta, Empresa empresa, String cargo, String area, Date aniosExperiencia,
			String profesion, String nivelEstudios, String tipoContrato, double salario) {
		this.idOferta = idOferta;
		this.empresa = empresa;
		this.cargo = cargo;
		this.area = area;
		this.aniosExperiencia = aniosExperiencia;
		this.profesion = profesion;
		this.nivelEstudios = nivelEstudios;
		this.tipoContrato = tipoContrato;
		this.salario = salario;
	}

	@Id

	@Column(name = "id_oferta", unique = true, nullable = false)
	public int getIdOferta() {
		return this.idOferta;
	}

	public void setIdOferta(int idOferta) {
		this.idOferta = idOferta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_empresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "cargo", nullable = false, length = 45)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "area", nullable = false, length = 45)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "anios_experiencia", nullable = false, length = 10)
	public Date getAniosExperiencia() {
		return this.aniosExperiencia;
	}

	public void setAniosExperiencia(Date aniosExperiencia) {
		this.aniosExperiencia = aniosExperiencia;
	}

	@Column(name = "profesion", nullable = false, length = 45)
	public String getProfesion() {
		return this.profesion;
	}

	public void setProfesion(String profesion) {
		this.profesion = profesion;
	}

	@Column(name = "nivel_estudios", nullable = false, length = 45)
	public String getNivelEstudios() {
		return this.nivelEstudios;
	}

	public void setNivelEstudios(String nivelEstudios) {
		this.nivelEstudios = nivelEstudios;
	}

	@Column(name = "tipo_contrato", nullable = false, length = 45)
	public String getTipoContrato() {
		return this.tipoContrato;
	}

	public void setTipoContrato(String tipoContrato) {
		this.tipoContrato = tipoContrato;
	}

	@Column(name = "salario", nullable = false, precision = 22, scale = 0)
	public double getSalario() {
		return this.salario;
	}

	public void setSalario(double salario) {
		this.salario = salario;
	}

}
