package com.edu.ubosque.model;
// Generated 23/11/2020, 6:36:43 p. m. by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clase que modela la oferta laboral
 * OfertaLaboral generated by hbm2java
 * @author Nicolás Ávila, Sebastián Moncaleano, Diego Torres | Universidad El Bosque
 */
@Entity
@Table(name = "oferta_laboral")
public class OfertaLaboral implements java.io.Serializable {

	private int idOferta;
	private Empresa empresa;
	private String cargo;
	private String area;
	private int aniosExperiencia;
	private String profesion;
	private String nivelEstudios;
	private String tipoContrato;
	private double salario;
	private Set<PostulacionLaboral> postulacionLaborals = new HashSet<PostulacionLaboral>(0);

	public OfertaLaboral() {
	}

	public OfertaLaboral(int idOferta, Empresa empresa, String cargo, String area, int aniosExperiencia,
			String profesion, String nivelEstudios, String tipoContrato, double salario) {
		this.idOferta = idOferta;
		this.empresa = empresa;
		this.cargo = cargo;
		this.area = area;
		this.aniosExperiencia = aniosExperiencia;
		this.profesion = profesion;
		this.nivelEstudios = nivelEstudios;
		this.tipoContrato = tipoContrato;
		this.salario = salario;
	}

	public OfertaLaboral(int idOferta, Empresa empresa, String cargo, String area, int aniosExperiencia,
			String profesion, String nivelEstudios, String tipoContrato, double salario,
			Set<PostulacionLaboral> postulacionLaborals) {
		this.idOferta = idOferta;
		this.empresa = empresa;
		this.cargo = cargo;
		this.area = area;
		this.aniosExperiencia = aniosExperiencia;
		this.profesion = profesion;
		this.nivelEstudios = nivelEstudios;
		this.tipoContrato = tipoContrato;
		this.salario = salario;
		this.postulacionLaborals = postulacionLaborals;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id_oferta", unique = true, nullable = false)
	public int getIdOferta() {
		return this.idOferta;
	}

	public void setIdOferta(int idOferta) {
		this.idOferta = idOferta;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_empresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "cargo", nullable = false, length = 45)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "area", nullable = false, length = 45)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "anios_experiencia", nullable = false)
	public int getAniosExperiencia() {
		return this.aniosExperiencia;
	}

	public void setAniosExperiencia(int aniosExperiencia) {
		this.aniosExperiencia = aniosExperiencia;
	}

	@Column(name = "profesion", nullable = false, length = 45)
	public String getProfesion() {
		return this.profesion;
	}

	public void setProfesion(String profesion) {
		this.profesion = profesion;
	}

	@Column(name = "nivel_estudios", nullable = false, length = 45)
	public String getNivelEstudios() {
		return this.nivelEstudios;
	}

	public void setNivelEstudios(String nivelEstudios) {
		this.nivelEstudios = nivelEstudios;
	}

	@Column(name = "tipo_contrato", nullable = false, length = 45)
	public String getTipoContrato() {
		return this.tipoContrato;
	}

	public void setTipoContrato(String tipoContrato) {
		this.tipoContrato = tipoContrato;
	}

	@Column(name = "salario", nullable = false, precision = 22, scale = 0)
	public double getSalario() {
		return this.salario;
	}

	public void setSalario(double salario) {
		this.salario = salario;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "ofertaLaboral")
	public Set<PostulacionLaboral> getPostulacionLaborals() {
		return this.postulacionLaborals;
	}

	public void setPostulacionLaborals(Set<PostulacionLaboral> postulacionLaborals) {
		this.postulacionLaborals = postulacionLaborals;
	}

}
