package com.edu.ubosque.model;
// Generated 23/11/2020, 6:36:43 p. m. by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Clase que modela la postulacion laboral
 * PostulacionLaboral generated by hbm2java
 * @author Nicolás Ávila, Sebastián Moncaleano, Diego Torres | Universidad El Bosque
 */
@Entity
@Table(name = "postulacion_laboral")
public class PostulacionLaboral implements java.io.Serializable {

	private int id;
	private Ciudadano ciudadano;
	private OfertaLaboral ofertaLaboral;

	public PostulacionLaboral() {
	}

	public PostulacionLaboral(Ciudadano ciudadano, OfertaLaboral ofertaLaboral) {
		this.ciudadano = ciudadano;
		this.ofertaLaboral = ofertaLaboral;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_ciudadano", nullable = false)
	public Ciudadano getCiudadano() {
		return this.ciudadano;
	}

	public void setCiudadano(Ciudadano ciudadano) {
		this.ciudadano = ciudadano;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_oferta", nullable = false)
	public OfertaLaboral getOfertaLaboral() {
		return this.ofertaLaboral;
	}

	public void setOfertaLaboral(OfertaLaboral ofertaLaboral) {
		this.ofertaLaboral = ofertaLaboral;
	}

}
