package com.edu.ubosque.model;
// Generated 14/11/2020, 11:42:56 a. m. by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Referencias generated by hbm2java
 */
@Entity
@Table(name = "referencias")
public class Referencias implements java.io.Serializable {

	private int id;
	private String tipoReferencia;
	private String nombre;
	private String relacion;
	private String cargo;
	private int telefono;
	private String direccion;
	private Set<Ciudadano> ciudadanos = new HashSet<Ciudadano>(0);

	public Referencias() {
	}

	public Referencias(int id, String tipoReferencia, String nombre, String relacion, String cargo, int telefono,
			String direccion) {
		this.id = id;
		this.tipoReferencia = tipoReferencia;
		this.nombre = nombre;
		this.relacion = relacion;
		this.cargo = cargo;
		this.telefono = telefono;
		this.direccion = direccion;
	}

	public Referencias(int id, String tipoReferencia, String nombre, String relacion, String cargo, int telefono,
			String direccion, Set<Ciudadano> ciudadanos) {
		this.id = id;
		this.tipoReferencia = tipoReferencia;
		this.nombre = nombre;
		this.relacion = relacion;
		this.cargo = cargo;
		this.telefono = telefono;
		this.direccion = direccion;
		this.ciudadanos = ciudadanos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "tipo_referencia", nullable = false, length = 45)
	public String getTipoReferencia() {
		return this.tipoReferencia;
	}

	public void setTipoReferencia(String tipoReferencia) {
		this.tipoReferencia = tipoReferencia;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "relacion", nullable = false, length = 45)
	public String getRelacion() {
		return this.relacion;
	}

	public void setRelacion(String relacion) {
		this.relacion = relacion;
	}

	@Column(name = "cargo", nullable = false, length = 45)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "telefono", nullable = false)
	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	@Column(name = "direccion", nullable = false, length = 60)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "referencias")
	public Set<Ciudadano> getCiudadanos() {
		return this.ciudadanos;
	}

	public void setCiudadanos(Set<Ciudadano> ciudadanos) {
		this.ciudadanos = ciudadanos;
	}

}
