package com.edu.ubosque.model;
// Generated 16/11/2020, 12:57:07 a. m. by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Referencias generated by hbm2java
 */
@Entity
@Table(name = "referencias")
public class Referencias implements java.io.Serializable {

	private int id;
	private Ciudadano ciudadano;
	private String tipoReferencia;
	private String nombre;
	private String relacion;
	private String cargo;
	private int telefono;
	private String direccion;

	public Referencias() {
	}

	public Referencias(int id, Ciudadano ciudadano, String tipoReferencia, String nombre, String relacion, String cargo,
			int telefono, String direccion) {
		this.id = id;
		this.ciudadano = ciudadano;
		this.tipoReferencia = tipoReferencia;
		this.nombre = nombre;
		this.relacion = relacion;
		this.cargo = cargo;
		this.telefono = telefono;
		this.direccion = direccion;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ciudadano", nullable = false)
	public Ciudadano getCiudadano() {
		return this.ciudadano;
	}

	public void setCiudadano(Ciudadano ciudadano) {
		this.ciudadano = ciudadano;
	}

	@Column(name = "tipo_referencia", nullable = false, length = 45)
	public String getTipoReferencia() {
		return this.tipoReferencia;
	}

	public void setTipoReferencia(String tipoReferencia) {
		this.tipoReferencia = tipoReferencia;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "relacion", nullable = false, length = 45)
	public String getRelacion() {
		return this.relacion;
	}

	public void setRelacion(String relacion) {
		this.relacion = relacion;
	}

	@Column(name = "cargo", nullable = false, length = 45)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "telefono", nullable = false)
	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	@Column(name = "direccion", nullable = false, length = 60)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

}
